name: 'Setup Node.js with NPM Registry'
description: 'Setup Node.js with GitHub package registry, prepare .npmrc, and install dependencies'

inputs:
  github-token:
    description: 'GitHub token for npm registry authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 🔧 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@torian12321'

    - name: 🔑 Prepare .npmrc from example
      run: |
        cp .npmrc.example .npmrc
        sed -i "s|NPMRC_NODE_AUTH_TOKEN|${{ inputs.github-token }}|g" .npmrc
      shell: bash

    - name: 📦 Install dependencies
      run: npm install
      shell: bash
